# 1. Notifications
# notifications:

# 2. Env
env:
  global:
    - SF_LOG_BOOTSTRAP=true

# 3. Git
branches:
  only:
    - /^travis/ # travis branches
    - master

# 4. Bootstrap
# os: linux
# dist: xenial
language: generic
# addons:
before_cache: ./.ci.sh before_cache
cache:
  directories:
    # common
    - $HOME/.local
    - $HOME/.npm
    # darwin
    - $HOME/Library/Caches/Homebrew
    - $HOME/Library/Caches/pip
    # linux
    - $HOME/.cache/Homebrew
    - $HOME/.cache/pip

# 5. Steps
before_install: ./.ci.sh before_install
install: ./.ci.sh install
before_script: ./.ci.sh before_script
script: ./.ci.sh script
after_success: ./.ci.sh after_success
after_failure: ./.ci.sh after_failure
after_script: ./.ci.sh after_script

# 6. Deploy
before_deploy: ./.ci.sh before_deploy
# deploy:
after_deploy: ./.ci.sh after_deploy


jobs:
  include:
    - &stage-linux-bionic-minimal
      stage: test
      name: "Linux Bionic 18.04 with minimal brew"
      os: linux
      dist: bionic
      env: CACHE_NAME=linux-bionic-minimal SF_CI_BREW_INSTALL=minimal
